language: python
python:
  - "3.6"
install: "pip install ."
script:
  - "py.test -v tests/test_dates.py"

after_success:
  - git config --global user.name "semantic-release (via TravisCI)"
  - git config --global user.email "semantic-release@travis"
  - pip install python-semantic-release
  - semantic-release publish